name: "build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    # We use Ubuntu 20.04 as it comes with GCC v9.3 by default.
    runs-on: ubuntu-20.04
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        # See https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        key: build-${{ runner.os }}-${{ hashFiles('**/*_deps.bzl') }}-${{ hashFiles('**/*.bzl', '**/*.bazel') }}
        restore-keys: |
          build-${{ runner.os }}-${{ hashFiles('**/*_deps.bzl') }}
          build-${{ runner.os }}-

    - name: Install p4c system dependencies (Flex, Bison, GMP)
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev libgmp-dev

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.1/$BAZEL"
        chmod +x $BAZEL

    - name: Build
      run: ./$BAZEL build //... --distinct_host_configuration=false

  test:
    # We use Ubuntu 20.04 as it comes with GCC v9.3 by default.
    runs-on: ubuntu-20.04
    env:
      BAZEL: bazelisk-linux-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: "~/.cache/bazel"
        key: test-${{ runner.os }}-${{ hashFiles('**/*_deps.bzl') }}-${{ hashFiles('**/*.bzl', '**/*.bazel') }}
        restore-keys: |
          test-${{ runner.os }}-${{ hashFiles('**/*_deps.bzl') }}
          test-${{ runner.os }}-

    - name: Install p4c system dependencies (Flex, Bison, GMP)
      run: sudo apt-get update && sudo apt-get install bison flex libfl-dev libgmp-dev

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.1/$BAZEL"
        chmod +x $BAZEL

    - name: Test
      run: ./$BAZEL test //... --test_output=errors --distinct_host_configuration=false
